version: '3'

services:
  app:
    container_name: app
    build: .
    depends_on:
      - 'mongo'
    links: 
      - mongo
    ports: 
      - '3002:3002'

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'